all: run

run:
	g++ -std=c++11 -I"D:/ProgramPack/C++/SFML-2.6.1/include" chess.cpp Pieces.cpp Board.cpp -L"D:/ProgramPack/C++/SFML-2.6.1/lib" -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -o main.exe
	./main.exe